runtime: custom
#runtime: python37
#entrypoint: python manage.py collectstatic --no-input && gunicorn -b :$PORT backend.wsgi
#entrypoint: gunicorn -b :$PORT backend.wsgi
env: flex
entrypoint: python3 manage.py runserver 0.0.0.0:$PORT

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: phoenix-253808:europe-west6:phoenix-253808=tcp:5432
