# Generated by Django 2.2.6 on 2019-10-24 15:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_time', models.DateTimeField()),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_station', to='trips.Station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_station', to='trips.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TripTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Ticket')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Trip')),
            ],
        ),
    ]
