# Generated by Django 2.2.6 on 2019-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripticket',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tripticket',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='ticket',
            field=models.CharField(default='SINGLE_TRIP_TICKET', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='ticket_price',
            field=models.FloatField(default=3.3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TripTicket',
        ),
    ]
