# Generated by Django 2.2.6 on 2019-11-11 13:25

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20191028_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('zones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
