# Generated by Django 2.2.6 on 2019-11-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_stationv2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationv2',
            name='zones',
        ),
    ]
