# Generated by Django 2.2.7 on 2019-11-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_stationv2_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_station', to='trips.StationV2'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_station', to='trips.StationV2'),
        ),
    ]
